# Generated by Django 4.1 on 2023-05-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_managers_remove_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
